Project NBA {
  database_type: 'PostgreSQL'
  Note: '''
    # NBA Player, Game, and Team statistics
    This database was created by the PhD students. If there are problems it’s their fault.
  '''
}
Table player_game as PG {
game_id varchar [pk]
player_id varchar [pk]
starter int  
mp varchar 
fg int  
fga int  
fg_pct float
fg3   int  
fg3a  int  
fg3_pct  float
ft   int  
fta int  
ft_pct float
orb int  
drb int  
trb int  
ast int  
stl int  
blk int  
tov int  
pf int   
pts int
plus_minus int 
did_not_play int 
is_inactive int
ts_pct float
efg_pct float
fg3a_per_fga_pct float
fta_per_fga_pct float
orb_pct float
drb_pct float
trb_pct float
ast_pct float
stl_pct float
blk_pct float
tov_pct float
usg_pct float
off_rtg int  
def_rtg int  
bpm float
minutes float
double_double int  
triple_double int  
DKP float
FDP float
SDP float
DKP_per_minute object 
FDP_per_minute object 
SDP_per_minute object 
pf_per_minute float
ts float
last_60_minutes_per_game_starting float
last_60_minutes_per_game_bench float
PGpct float
SGpct float
SFpct float
PFpct float
Cpct  float
active_position_minutes float
  note: "Data on individual player’s stats in each game"
}
Table team_game as TG{
  game_id varchar [pk]
  Team_Abbrev varchar [pk]
  H_A varchar 
  Team_Score int  
  Team_pace float
  Team_efg_pct float
  Team_tov_pct float  
  Team_orb_pct float
  Team_ft_rate float
  Team_off_rtg float
  Opponent_Abbrev varchar
  note: "Data on team stats in each game"
}
Table games as G{
   game_id varchar [pk]
   game_date  varchar
   OT int
   season int
  note: "General (non-stat) information about each game"
}

Table players as P{
  player_id varchar [pk]
  player varchar
  note: 'Players’ names'
}



Ref: PG.player_id > P.player_id 
Ref: PG.game_id > G.game_id
Ref: PG.game_id > TG.game_id
Ref: TG.game_id > G.game_id
Ref: TG.Team_Abbrev - TG.Opponent_Abbrev

